apiVersion: v1
kind: Secret
metadata:
  name: "split-pro-nextauth-secret"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "split-pro-nextauth-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $nextSecret := (get $secretData "split-pro-nextauth-secret") | default (randAlphaNum 32 | b64enc) }}
  nextauth-secret: {{ $nextSecret | quote }}
